### PR TITLE
usb: Read RSA keypair from user home or generate them

### PR DESCRIPTION
**Pull request by lavafroth**
### Changes
- Use the `homedir` crate to figure out the current user's home directory instead of the hardcoded path.
- Attempt to read the ADB RSA public and private keys from the `.android` directory inside the user home.
- On failure to read said keypair, we resort to generating ephemeral keypairs.
- Allow user to supply their own keypair using CLI flags.

### CODE REVIEW

**Comment by cocool97** [comment]
Thanks for doing it, this is something I wanted to clean when everything was working fine !

I thought about also allowing users to provide a custom private key with a clap option, can you add it to your PR ?

**Comment by lavafroth** [comment]
Yes, I'll add that.

**Comment by lavafroth** [comment]
Would you like the program to only accept the private key since we can derive the public key from the former?

**Comment by cocool97** [comment]
Only the private key yes, the program will automatically derive the public key from it. We could do the same for the "classical" process without having to load adbkey.pub

**Comment by lavafroth** [comment]
Sure, let's go for that. Also, should we keep the private in our `ADBUSBDevice` struct or should we keep the signing key. I reckon, the signing key is probably what we'd need for the rest of a connection anyways.

**Comment by cocool97** [comment]
Yes I don't think we need anything else because the signing key is derived from the private key if I remember correctly. Let's keep it inside the struct, this will prevent reloading the key for every command !

**Comment by lavafroth** [comment]
Ok, now the PR should suffice our requirements!

**Comment by lavafroth** [comment]
Also, you may create some github issues and assign them to me to share the development workload.

**Comment by cocool97** [comment]
Thanks for the work, I'll have a closer look at it this week but everything looks fine to me !

**Comment by lavafroth** [comment]
awesome!

**Comment by cocool97** [comment]
Had to remove some `unwrap` + `expect` and rework how public key is loaded into the program (used `from_der()`) + base64 to ease the loading.

**Comment by lavafroth** [comment]
Sure, yeah, that's a good way to do it as well. Thanks!

**Pull request merged**
