### PR TITLE
support mdns command through adb server with server-status

### PR DESCRIPTION
**Pull request by JinkeJ**

### CODE REVIEW

**Comment by cocool97** [comment]
Thanks for the PR, will have a look at it asap !

**Comment by cocool97** [comment]
I had a look at the code and it looks good to me, I just made a few changes to it. Can you try and validate that nothing broke ? I removed the `connect_with_envs()` method and added a `start_server()` method that can take environment variable if needed.

For the varint parsing, couldn't we use a crate [like](https://crates.io/crates/varint-rs) and therefore remove this parser from adb_client ?

**Comment by JinkeJ** [comment]
The structure of server status is protobuf. You can replace the function with a crate.

**Comment by JinkeJ** [comment]
https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/adb/proto/adb_host.proto;l=64?q=AdbServerStatus&sq=

**Comment by cocool97** [comment]
Is everything still working as expected with my modifications ? 

I can't test it as my server does not support mdns and server-status..

**Comment by JinkeJ** [comment]
It seems that "start_server" runs twice if we run mdns_force_openscreen_backend.
Furthermore, ServerStatus fmt function should keep output same as adb, that is only writeln when usb_backend_forced or mdns_backend_forced is true.

**Comment by JinkeJ** [comment]
Any update?

**Comment by cocool97** [comment]
Hey, sorry for the delay !

I looked at your code, the only thing missing is adding a `mdns check` subcommand to adb_cli in order to provide the same functionalities as the official binary. 

Can you handle it ? I'll merge it afterwards

**Comment by JinkeJ** [comment]
running ```start_server``` twice causes the stuck of starting new process, because when the first process haven't lifted up, the second process will try to start the server again.

**Comment by cocool97** [comment]
Would you mind having a look at it ? I'm afraid I won't have time in the next few days..

**Comment by JinkeJ** [comment]
I will have a try, but might need to define a new function or corrupt current existing function

**Comment by cocool97** [comment]
No problem, I'm planning on releasing a `v2.2` with mdns

**Comment by JinkeJ** [comment]
@cocool97 Please resolve the conflict with main branch because I didn't pull the mdns branch to my local.

**Comment by JinkeJ** [comment]
mdns check, mdns devices, reconnect, reconnect offline, tcpip, usb, forwardremoveall, reverseremoveall, server-status

Those features are added in these commits.

**Comment by cocool97** [comment]
Thanks, I'll rebase it asap

**Comment by cocool97** [comment]
Double `start_server` is now fixed ?

**Comment by JinkeJ** [comment]
Yes, I removed start_server, because connect will start too.

**Pull request merged**
