### PR TITLE
Add pairing and connecting features over tcp

### PR DESCRIPTION
**Pull request by vmillet-dev**
As we discussed here #10, I implemented pair and connect command and fix displaiying devices with long format

### CODE REVIEW

**Comment by cocool97** [comment]
Thanks for the PR, you specify in the error field that pairing is needed before connecting a device to wifi. I think that this is mandatory before any action on a device (wifi connected / wired), isn't it ?

**Comment by vmillet-dev** [comment]
Yes, maybe it's too much, I can remove that if you want

**Comment by cocool97** [comment]
Yes, plz. This will be more accurate

**Comment by cocool97** [comment]
Thanks for your PR ! 

I added a disconnect command + rework to fit the new code arhitecture ;)

**Pull request merged**
