### PR TITLE
#9 Add windows support

### PR DESCRIPTION
**Pull request by vmillet-dev**
I had problems compiling on windows, I saw that it was already known #9, I just conditioned termios and the interacive shell to compile only for unix.

After that, the question is: how do you implement it on windows?

### CODE REVIEW

**Comment by cocool97** [comment]
I don't have a Windows machine to test it on, but `ADBTermios` struct is basically just here to set and restore a termios state. Have you tested to just remove these references in shell.rs file and launch it ?

**Comment by vmillet-dev** [comment]
I tried what you said and  indeed, it does work on my Win10, we can use the interactive shell but the dep to termios still needs to be conditioned by unix.

Here a sceenshot of my terminal :

image

I'll update my PR

**Comment by cocool97** [comment]
Sounds good then ! Of course `termios` needs to be a Unix-only dependency. 

Two more things to be sure it really works :
- Can you try launching it via PowerShell too ?
- On a deeper level, are input sent to server directly when entered ? This is what termios was used to, but if Windows handles it directly this is good.

Thanks

**Comment by vmillet-dev** [comment]
About your first question, the answer is yes

image

Now, for the second one, I don't know how to check that to be honest

**Comment by cocool97** [comment]
If you want, you can check in tools like Wireshark in gui or tcpdump if TCP data is sent at every keystroke 

But if you say that this is "interactive", this is probably the case

Once you validate this I will validate this PR

**Comment by vmillet-dev** [comment]
So from what I see, It's not at each keystroke but after hitting "Enter" in windows. I can check if I found something as workaround

**Comment by NutchapolSal** [comment]
Would it be possible to move `ADBServerDevice.shell()` into `adb_cli` or somewhere else?
IMO it's strange having a method like that in a library in the first place.

**Comment by cocool97** [comment]
@NutchapolSal why do you find it strange ? 

ADB exposes shell functionality, I think that this is normal to have such a function implemented in the library, and not in the client. 

This function should be hidden behind a `cfg` to ensure that it is not available but I truly think that it fits in this library.

**Comment by NutchapolSal** [comment]
> why do you find it strange ?

I think it's because while the rest of the library is for use with other code, this method takes control of stdin/stdout and does something to the terminal directly.
Actually, if this method doesn't interact with the terminal, but instead returns (for example) a pair of `mpsc::Sender` and `Receiver` for the device's input and output so library users can send multiple commands without having to start a new shell connection, that would be much better.

I want to use this library for a project I'm working on right now, but I'm on Windows, so I've tried removing `ADBServerDevice.shell()` and then the resulting unused code, turns out this also takes out `mio` from `adb_client`'s dependencies.

**Comment by cocool97** [comment]
Yes you're right, we can either use mpsc or just require a Read (that could be stdin) and a Write (that could be anything we want to write result to).

Feel free to provide an implementation, I'll have a look at it this week ! 

And yes, using a cfg will require to setup mio only for unix plateforms as well !

**Comment by cocool97** [comment]
@vmillet-dev @NutchapolSal can you confirm that PR #35 works on windows ? 

I moved ADBTermios in the CLI, and now pass a Writer and a Reader to `.shell()`

**Comment by cocool97** [comment]
Closing as done in another PR

**Pull request closed without merging**
